name: testRobot
on: workflow_call
jobs:
  testit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: useAction
        uses: breaking153/SecCrawler-Action@master

